services:
  prometheus:
    image: prom/prometheus:v2.37.9
    networks:
      coherence:
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - 9090:9090

  grafana:
    networks:
      coherence:
    image: grafana/grafana:10.0.13
#    image: grafana/grafana:11.3.0
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/dashboards
    ports:
      - 3000:3000

networks:
  coherence:
