global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'Prometheus'
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: 'coherence_cluster'
    static_configs:
      - targets: ["172.17.0.1:9612", "172.17.0.1:9613"]
